FROM golang:1.14

WORKDIR /app
COPY . .

ENV TOKEN=DISCORD_TOKEN
ENV AWS_ACCESS_KEY_ID=AKID
ENV AWS_SECRET_ACCESS_KEY=SAK
ENV AWS_DEFAULT_REGION=REGION
ENV FUNCTION=LAMBDAFUNCTION

RUN go build -o main .
CMD ["/app/main"]