on: [push, pull_request]
name: build
jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: go build .
        
  docker:
    runs-on: ubuntu-latest
    steps:     
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        id: docker_build
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/observerbot:latest \
          .
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}